spring.application.name=Stage
spring.threads.virtual.enabled=true
server.port=8090
spring.datasource.url=jdbc:h2:mem:stage
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
llm.provider=groq
groq.api.key=${GROQ_API_KEY}