# LLM API Keys
llm.groq.api-key=none
llm.azure.endpoint=none
llm.azure.deployment=gpt-4o
llm.claude.api-key=none
llm.openai.api-key=none
llm.gemini.api-key=none
llm.azure.api-key=none
# Server
server.port=8090
spring.threads.virtual.enabled=true

# Database H2
spring.datasource.url=jdbc:h2:mem:stage
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true